language: node_js

node_js:
  - "8"
  - "10"

cache: yarn

script:
  - yarn build

os:
  - linux
  - osx
  - windows

after_success: if [[ "$TRAVIS_OS_NAME" != 'windows' ]]; then echo "All Done" && exit 0; fi
