// GENERATED CODE -- DO NOT EDIT!

// package: huddly
// file: proto/huddly.proto

import * as proto_huddly_pb from "../proto/huddly_pb";
import * as google_protobuf_empty_pb from "google-protobuf/google/protobuf/empty_pb";
import * as google_protobuf_timestamp_pb from "google-protobuf/google/protobuf/timestamp_pb";
import * as grpc from "@grpc/grpc-js";

interface IHuddlyServiceService extends grpc.ServiceDefinition<grpc.UntypedServiceImplementation> {
  upgradeDevice: grpc.MethodDefinition<proto_huddly_pb.Chunk, proto_huddly_pb.DeviceStatus>;
  upgradeVerify: grpc.MethodDefinition<proto_huddly_pb.Chunk, proto_huddly_pb.DeviceStatus>;
  reset: grpc.MethodDefinition<google_protobuf_empty_pb.Empty, proto_huddly_pb.DeviceStatus>;
  getDeviceName: grpc.MethodDefinition<google_protobuf_empty_pb.Empty, proto_huddly_pb.DeviceName>;
  getDeviceVersion: grpc.MethodDefinition<google_protobuf_empty_pb.Empty, proto_huddly_pb.DeviceVersion>;
  getBootloaderVersion: grpc.MethodDefinition<google_protobuf_empty_pb.Empty, proto_huddly_pb.DeviceVersion>;
  getDevicePackages: grpc.MethodDefinition<google_protobuf_empty_pb.Empty, proto_huddly_pb.DeviceVersion>;
  getBootSlot: grpc.MethodDefinition<google_protobuf_empty_pb.Empty, proto_huddly_pb.BootSlot>;
  setBootSlot: grpc.MethodDefinition<proto_huddly_pb.BootSlot, proto_huddly_pb.DeviceStatus>;
  upgradeBootLoader: grpc.MethodDefinition<proto_huddly_pb.Chunk, proto_huddly_pb.DeviceStatus>;
  setIpv4: grpc.MethodDefinition<proto_huddly_pb.Ipv4Config, proto_huddly_pb.DeviceStatus>;
  setPTZ: grpc.MethodDefinition<proto_huddly_pb.PTZ, proto_huddly_pb.DeviceStatus>;
  getPTZ: grpc.MethodDefinition<google_protobuf_empty_pb.Empty, proto_huddly_pb.PTZ>;
  getLogFiles: grpc.MethodDefinition<proto_huddly_pb.LogFile, proto_huddly_pb.Chunk>;
  eraseLogFile: grpc.MethodDefinition<proto_huddly_pb.LogFile, proto_huddly_pb.DeviceStatus>;
  getTemperatures: grpc.MethodDefinition<google_protobuf_empty_pb.Empty, proto_huddly_pb.Temperatures>;
  resetPtzTransition: grpc.MethodDefinition<google_protobuf_empty_pb.Empty, proto_huddly_pb.DeviceStatus>;
  getCropIndex: grpc.MethodDefinition<google_protobuf_empty_pb.Empty, proto_huddly_pb.CropIndexStatusResponse>;
  ptzTransition: grpc.MethodDefinition<proto_huddly_pb.IndexedTransitions, proto_huddly_pb.IndexedTransitionsResponse>;
  getCurrentPtzCrop: grpc.MethodDefinition<google_protobuf_empty_pb.Empty, proto_huddly_pb.CurrentPtzCrop>;
  setCnnFeature: grpc.MethodDefinition<proto_huddly_pb.CnnFeature, proto_huddly_pb.DeviceStatus>;
  getCnnFeatureStatus: grpc.MethodDefinition<proto_huddly_pb.CnnFeature, proto_huddly_pb.CNNStatus>;
  getUptime: grpc.MethodDefinition<google_protobuf_empty_pb.Empty, proto_huddly_pb.Uptime>;
  setTimezone: grpc.MethodDefinition<proto_huddly_pb.Timezone, proto_huddly_pb.DeviceStatus>;
  getTimezone: grpc.MethodDefinition<google_protobuf_empty_pb.Empty, proto_huddly_pb.Timezone>;
  setTime: grpc.MethodDefinition<google_protobuf_timestamp_pb.Timestamp, proto_huddly_pb.DeviceStatus>;
  getTime: grpc.MethodDefinition<google_protobuf_empty_pb.Empty, google_protobuf_timestamp_pb.Timestamp>;
  setBrightness: grpc.MethodDefinition<proto_huddly_pb.Brightness, proto_huddly_pb.DeviceStatus>;
  getBrightness: grpc.MethodDefinition<google_protobuf_empty_pb.Empty, proto_huddly_pb.Brightness>;
  getRawBuffer: grpc.MethodDefinition<google_protobuf_empty_pb.Empty, proto_huddly_pb.Chunk>;
  getVideoFormats: grpc.MethodDefinition<google_protobuf_empty_pb.Empty, proto_huddly_pb.VideoFormats>;
}

export const HuddlyServiceService: IHuddlyServiceService;

export interface IHuddlyServiceServer extends grpc.UntypedServiceImplementation {
  upgradeDevice: grpc.handleClientStreamingCall<proto_huddly_pb.Chunk, proto_huddly_pb.DeviceStatus>;
  upgradeVerify: grpc.handleClientStreamingCall<proto_huddly_pb.Chunk, proto_huddly_pb.DeviceStatus>;
  reset: grpc.handleUnaryCall<google_protobuf_empty_pb.Empty, proto_huddly_pb.DeviceStatus>;
  getDeviceName: grpc.handleUnaryCall<google_protobuf_empty_pb.Empty, proto_huddly_pb.DeviceName>;
  getDeviceVersion: grpc.handleUnaryCall<google_protobuf_empty_pb.Empty, proto_huddly_pb.DeviceVersion>;
  getBootloaderVersion: grpc.handleUnaryCall<google_protobuf_empty_pb.Empty, proto_huddly_pb.DeviceVersion>;
  getDevicePackages: grpc.handleUnaryCall<google_protobuf_empty_pb.Empty, proto_huddly_pb.DeviceVersion>;
  getBootSlot: grpc.handleUnaryCall<google_protobuf_empty_pb.Empty, proto_huddly_pb.BootSlot>;
  setBootSlot: grpc.handleUnaryCall<proto_huddly_pb.BootSlot, proto_huddly_pb.DeviceStatus>;
  upgradeBootLoader: grpc.handleClientStreamingCall<proto_huddly_pb.Chunk, proto_huddly_pb.DeviceStatus>;
  setIpv4: grpc.handleUnaryCall<proto_huddly_pb.Ipv4Config, proto_huddly_pb.DeviceStatus>;
  setPTZ: grpc.handleUnaryCall<proto_huddly_pb.PTZ, proto_huddly_pb.DeviceStatus>;
  getPTZ: grpc.handleUnaryCall<google_protobuf_empty_pb.Empty, proto_huddly_pb.PTZ>;
  getLogFiles: grpc.handleServerStreamingCall<proto_huddly_pb.LogFile, proto_huddly_pb.Chunk>;
  eraseLogFile: grpc.handleUnaryCall<proto_huddly_pb.LogFile, proto_huddly_pb.DeviceStatus>;
  getTemperatures: grpc.handleUnaryCall<google_protobuf_empty_pb.Empty, proto_huddly_pb.Temperatures>;
  resetPtzTransition: grpc.handleUnaryCall<google_protobuf_empty_pb.Empty, proto_huddly_pb.DeviceStatus>;
  getCropIndex: grpc.handleUnaryCall<google_protobuf_empty_pb.Empty, proto_huddly_pb.CropIndexStatusResponse>;
  ptzTransition: grpc.handleUnaryCall<proto_huddly_pb.IndexedTransitions, proto_huddly_pb.IndexedTransitionsResponse>;
  getCurrentPtzCrop: grpc.handleUnaryCall<google_protobuf_empty_pb.Empty, proto_huddly_pb.CurrentPtzCrop>;
  setCnnFeature: grpc.handleUnaryCall<proto_huddly_pb.CnnFeature, proto_huddly_pb.DeviceStatus>;
  getCnnFeatureStatus: grpc.handleUnaryCall<proto_huddly_pb.CnnFeature, proto_huddly_pb.CNNStatus>;
  getUptime: grpc.handleUnaryCall<google_protobuf_empty_pb.Empty, proto_huddly_pb.Uptime>;
  setTimezone: grpc.handleUnaryCall<proto_huddly_pb.Timezone, proto_huddly_pb.DeviceStatus>;
  getTimezone: grpc.handleUnaryCall<google_protobuf_empty_pb.Empty, proto_huddly_pb.Timezone>;
  setTime: grpc.handleUnaryCall<google_protobuf_timestamp_pb.Timestamp, proto_huddly_pb.DeviceStatus>;
  getTime: grpc.handleUnaryCall<google_protobuf_empty_pb.Empty, google_protobuf_timestamp_pb.Timestamp>;
  setBrightness: grpc.handleUnaryCall<proto_huddly_pb.Brightness, proto_huddly_pb.DeviceStatus>;
  getBrightness: grpc.handleUnaryCall<google_protobuf_empty_pb.Empty, proto_huddly_pb.Brightness>;
  getRawBuffer: grpc.handleServerStreamingCall<google_protobuf_empty_pb.Empty, proto_huddly_pb.Chunk>;
  getVideoFormats: grpc.handleUnaryCall<google_protobuf_empty_pb.Empty, proto_huddly_pb.VideoFormats>;
}

export class HuddlyServiceClient extends grpc.Client {
  constructor(address: string, credentials: grpc.ChannelCredentials, options?: object);
  upgradeDevice(callback: grpc.requestCallback<proto_huddly_pb.DeviceStatus>): grpc.ClientWritableStream<proto_huddly_pb.Chunk>;
  upgradeDevice(metadataOrOptions: grpc.Metadata | grpc.CallOptions | null, callback: grpc.requestCallback<proto_huddly_pb.DeviceStatus>): grpc.ClientWritableStream<proto_huddly_pb.Chunk>;
  upgradeDevice(metadata: grpc.Metadata | null, options: grpc.CallOptions | null, callback: grpc.requestCallback<proto_huddly_pb.DeviceStatus>): grpc.ClientWritableStream<proto_huddly_pb.Chunk>;
  upgradeVerify(callback: grpc.requestCallback<proto_huddly_pb.DeviceStatus>): grpc.ClientWritableStream<proto_huddly_pb.Chunk>;
  upgradeVerify(metadataOrOptions: grpc.Metadata | grpc.CallOptions | null, callback: grpc.requestCallback<proto_huddly_pb.DeviceStatus>): grpc.ClientWritableStream<proto_huddly_pb.Chunk>;
  upgradeVerify(metadata: grpc.Metadata | null, options: grpc.CallOptions | null, callback: grpc.requestCallback<proto_huddly_pb.DeviceStatus>): grpc.ClientWritableStream<proto_huddly_pb.Chunk>;
  reset(argument: google_protobuf_empty_pb.Empty, callback: grpc.requestCallback<proto_huddly_pb.DeviceStatus>): grpc.ClientUnaryCall;
  reset(argument: google_protobuf_empty_pb.Empty, metadataOrOptions: grpc.Metadata | grpc.CallOptions | null, callback: grpc.requestCallback<proto_huddly_pb.DeviceStatus>): grpc.ClientUnaryCall;
  reset(argument: google_protobuf_empty_pb.Empty, metadata: grpc.Metadata | null, options: grpc.CallOptions | null, callback: grpc.requestCallback<proto_huddly_pb.DeviceStatus>): grpc.ClientUnaryCall;
  getDeviceName(argument: google_protobuf_empty_pb.Empty, callback: grpc.requestCallback<proto_huddly_pb.DeviceName>): grpc.ClientUnaryCall;
  getDeviceName(argument: google_protobuf_empty_pb.Empty, metadataOrOptions: grpc.Metadata | grpc.CallOptions | null, callback: grpc.requestCallback<proto_huddly_pb.DeviceName>): grpc.ClientUnaryCall;
  getDeviceName(argument: google_protobuf_empty_pb.Empty, metadata: grpc.Metadata | null, options: grpc.CallOptions | null, callback: grpc.requestCallback<proto_huddly_pb.DeviceName>): grpc.ClientUnaryCall;
  getDeviceVersion(argument: google_protobuf_empty_pb.Empty, callback: grpc.requestCallback<proto_huddly_pb.DeviceVersion>): grpc.ClientUnaryCall;
  getDeviceVersion(argument: google_protobuf_empty_pb.Empty, metadataOrOptions: grpc.Metadata | grpc.CallOptions | null, callback: grpc.requestCallback<proto_huddly_pb.DeviceVersion>): grpc.ClientUnaryCall;
  getDeviceVersion(argument: google_protobuf_empty_pb.Empty, metadata: grpc.Metadata | null, options: grpc.CallOptions | null, callback: grpc.requestCallback<proto_huddly_pb.DeviceVersion>): grpc.ClientUnaryCall;
  getBootloaderVersion(argument: google_protobuf_empty_pb.Empty, callback: grpc.requestCallback<proto_huddly_pb.DeviceVersion>): grpc.ClientUnaryCall;
  getBootloaderVersion(argument: google_protobuf_empty_pb.Empty, metadataOrOptions: grpc.Metadata | grpc.CallOptions | null, callback: grpc.requestCallback<proto_huddly_pb.DeviceVersion>): grpc.ClientUnaryCall;
  getBootloaderVersion(argument: google_protobuf_empty_pb.Empty, metadata: grpc.Metadata | null, options: grpc.CallOptions | null, callback: grpc.requestCallback<proto_huddly_pb.DeviceVersion>): grpc.ClientUnaryCall;
  getDevicePackages(argument: google_protobuf_empty_pb.Empty, callback: grpc.requestCallback<proto_huddly_pb.DeviceVersion>): grpc.ClientUnaryCall;
  getDevicePackages(argument: google_protobuf_empty_pb.Empty, metadataOrOptions: grpc.Metadata | grpc.CallOptions | null, callback: grpc.requestCallback<proto_huddly_pb.DeviceVersion>): grpc.ClientUnaryCall;
  getDevicePackages(argument: google_protobuf_empty_pb.Empty, metadata: grpc.Metadata | null, options: grpc.CallOptions | null, callback: grpc.requestCallback<proto_huddly_pb.DeviceVersion>): grpc.ClientUnaryCall;
  getBootSlot(argument: google_protobuf_empty_pb.Empty, callback: grpc.requestCallback<proto_huddly_pb.BootSlot>): grpc.ClientUnaryCall;
  getBootSlot(argument: google_protobuf_empty_pb.Empty, metadataOrOptions: grpc.Metadata | grpc.CallOptions | null, callback: grpc.requestCallback<proto_huddly_pb.BootSlot>): grpc.ClientUnaryCall;
  getBootSlot(argument: google_protobuf_empty_pb.Empty, metadata: grpc.Metadata | null, options: grpc.CallOptions | null, callback: grpc.requestCallback<proto_huddly_pb.BootSlot>): grpc.ClientUnaryCall;
  setBootSlot(argument: proto_huddly_pb.BootSlot, callback: grpc.requestCallback<proto_huddly_pb.DeviceStatus>): grpc.ClientUnaryCall;
  setBootSlot(argument: proto_huddly_pb.BootSlot, metadataOrOptions: grpc.Metadata | grpc.CallOptions | null, callback: grpc.requestCallback<proto_huddly_pb.DeviceStatus>): grpc.ClientUnaryCall;
  setBootSlot(argument: proto_huddly_pb.BootSlot, metadata: grpc.Metadata | null, options: grpc.CallOptions | null, callback: grpc.requestCallback<proto_huddly_pb.DeviceStatus>): grpc.ClientUnaryCall;
  upgradeBootLoader(callback: grpc.requestCallback<proto_huddly_pb.DeviceStatus>): grpc.ClientWritableStream<proto_huddly_pb.Chunk>;
  upgradeBootLoader(metadataOrOptions: grpc.Metadata | grpc.CallOptions | null, callback: grpc.requestCallback<proto_huddly_pb.DeviceStatus>): grpc.ClientWritableStream<proto_huddly_pb.Chunk>;
  upgradeBootLoader(metadata: grpc.Metadata | null, options: grpc.CallOptions | null, callback: grpc.requestCallback<proto_huddly_pb.DeviceStatus>): grpc.ClientWritableStream<proto_huddly_pb.Chunk>;
  setIpv4(argument: proto_huddly_pb.Ipv4Config, callback: grpc.requestCallback<proto_huddly_pb.DeviceStatus>): grpc.ClientUnaryCall;
  setIpv4(argument: proto_huddly_pb.Ipv4Config, metadataOrOptions: grpc.Metadata | grpc.CallOptions | null, callback: grpc.requestCallback<proto_huddly_pb.DeviceStatus>): grpc.ClientUnaryCall;
  setIpv4(argument: proto_huddly_pb.Ipv4Config, metadata: grpc.Metadata | null, options: grpc.CallOptions | null, callback: grpc.requestCallback<proto_huddly_pb.DeviceStatus>): grpc.ClientUnaryCall;
  setPTZ(argument: proto_huddly_pb.PTZ, callback: grpc.requestCallback<proto_huddly_pb.DeviceStatus>): grpc.ClientUnaryCall;
  setPTZ(argument: proto_huddly_pb.PTZ, metadataOrOptions: grpc.Metadata | grpc.CallOptions | null, callback: grpc.requestCallback<proto_huddly_pb.DeviceStatus>): grpc.ClientUnaryCall;
  setPTZ(argument: proto_huddly_pb.PTZ, metadata: grpc.Metadata | null, options: grpc.CallOptions | null, callback: grpc.requestCallback<proto_huddly_pb.DeviceStatus>): grpc.ClientUnaryCall;
  getPTZ(argument: google_protobuf_empty_pb.Empty, callback: grpc.requestCallback<proto_huddly_pb.PTZ>): grpc.ClientUnaryCall;
  getPTZ(argument: google_protobuf_empty_pb.Empty, metadataOrOptions: grpc.Metadata | grpc.CallOptions | null, callback: grpc.requestCallback<proto_huddly_pb.PTZ>): grpc.ClientUnaryCall;
  getPTZ(argument: google_protobuf_empty_pb.Empty, metadata: grpc.Metadata | null, options: grpc.CallOptions | null, callback: grpc.requestCallback<proto_huddly_pb.PTZ>): grpc.ClientUnaryCall;
  getLogFiles(argument: proto_huddly_pb.LogFile, metadataOrOptions?: grpc.Metadata | grpc.CallOptions | null): grpc.ClientReadableStream<proto_huddly_pb.Chunk>;
  getLogFiles(argument: proto_huddly_pb.LogFile, metadata?: grpc.Metadata | null, options?: grpc.CallOptions | null): grpc.ClientReadableStream<proto_huddly_pb.Chunk>;
  eraseLogFile(argument: proto_huddly_pb.LogFile, callback: grpc.requestCallback<proto_huddly_pb.DeviceStatus>): grpc.ClientUnaryCall;
  eraseLogFile(argument: proto_huddly_pb.LogFile, metadataOrOptions: grpc.Metadata | grpc.CallOptions | null, callback: grpc.requestCallback<proto_huddly_pb.DeviceStatus>): grpc.ClientUnaryCall;
  eraseLogFile(argument: proto_huddly_pb.LogFile, metadata: grpc.Metadata | null, options: grpc.CallOptions | null, callback: grpc.requestCallback<proto_huddly_pb.DeviceStatus>): grpc.ClientUnaryCall;
  getTemperatures(argument: google_protobuf_empty_pb.Empty, callback: grpc.requestCallback<proto_huddly_pb.Temperatures>): grpc.ClientUnaryCall;
  getTemperatures(argument: google_protobuf_empty_pb.Empty, metadataOrOptions: grpc.Metadata | grpc.CallOptions | null, callback: grpc.requestCallback<proto_huddly_pb.Temperatures>): grpc.ClientUnaryCall;
  getTemperatures(argument: google_protobuf_empty_pb.Empty, metadata: grpc.Metadata | null, options: grpc.CallOptions | null, callback: grpc.requestCallback<proto_huddly_pb.Temperatures>): grpc.ClientUnaryCall;
  resetPtzTransition(argument: google_protobuf_empty_pb.Empty, callback: grpc.requestCallback<proto_huddly_pb.DeviceStatus>): grpc.ClientUnaryCall;
  resetPtzTransition(argument: google_protobuf_empty_pb.Empty, metadataOrOptions: grpc.Metadata | grpc.CallOptions | null, callback: grpc.requestCallback<proto_huddly_pb.DeviceStatus>): grpc.ClientUnaryCall;
  resetPtzTransition(argument: google_protobuf_empty_pb.Empty, metadata: grpc.Metadata | null, options: grpc.CallOptions | null, callback: grpc.requestCallback<proto_huddly_pb.DeviceStatus>): grpc.ClientUnaryCall;
  getCropIndex(argument: google_protobuf_empty_pb.Empty, callback: grpc.requestCallback<proto_huddly_pb.CropIndexStatusResponse>): grpc.ClientUnaryCall;
  getCropIndex(argument: google_protobuf_empty_pb.Empty, metadataOrOptions: grpc.Metadata | grpc.CallOptions | null, callback: grpc.requestCallback<proto_huddly_pb.CropIndexStatusResponse>): grpc.ClientUnaryCall;
  getCropIndex(argument: google_protobuf_empty_pb.Empty, metadata: grpc.Metadata | null, options: grpc.CallOptions | null, callback: grpc.requestCallback<proto_huddly_pb.CropIndexStatusResponse>): grpc.ClientUnaryCall;
  ptzTransition(argument: proto_huddly_pb.IndexedTransitions, callback: grpc.requestCallback<proto_huddly_pb.IndexedTransitionsResponse>): grpc.ClientUnaryCall;
  ptzTransition(argument: proto_huddly_pb.IndexedTransitions, metadataOrOptions: grpc.Metadata | grpc.CallOptions | null, callback: grpc.requestCallback<proto_huddly_pb.IndexedTransitionsResponse>): grpc.ClientUnaryCall;
  ptzTransition(argument: proto_huddly_pb.IndexedTransitions, metadata: grpc.Metadata | null, options: grpc.CallOptions | null, callback: grpc.requestCallback<proto_huddly_pb.IndexedTransitionsResponse>): grpc.ClientUnaryCall;
  getCurrentPtzCrop(argument: google_protobuf_empty_pb.Empty, callback: grpc.requestCallback<proto_huddly_pb.CurrentPtzCrop>): grpc.ClientUnaryCall;
  getCurrentPtzCrop(argument: google_protobuf_empty_pb.Empty, metadataOrOptions: grpc.Metadata | grpc.CallOptions | null, callback: grpc.requestCallback<proto_huddly_pb.CurrentPtzCrop>): grpc.ClientUnaryCall;
  getCurrentPtzCrop(argument: google_protobuf_empty_pb.Empty, metadata: grpc.Metadata | null, options: grpc.CallOptions | null, callback: grpc.requestCallback<proto_huddly_pb.CurrentPtzCrop>): grpc.ClientUnaryCall;
  setCnnFeature(argument: proto_huddly_pb.CnnFeature, callback: grpc.requestCallback<proto_huddly_pb.DeviceStatus>): grpc.ClientUnaryCall;
  setCnnFeature(argument: proto_huddly_pb.CnnFeature, metadataOrOptions: grpc.Metadata | grpc.CallOptions | null, callback: grpc.requestCallback<proto_huddly_pb.DeviceStatus>): grpc.ClientUnaryCall;
  setCnnFeature(argument: proto_huddly_pb.CnnFeature, metadata: grpc.Metadata | null, options: grpc.CallOptions | null, callback: grpc.requestCallback<proto_huddly_pb.DeviceStatus>): grpc.ClientUnaryCall;
  getCnnFeatureStatus(argument: proto_huddly_pb.CnnFeature, callback: grpc.requestCallback<proto_huddly_pb.CNNStatus>): grpc.ClientUnaryCall;
  getCnnFeatureStatus(argument: proto_huddly_pb.CnnFeature, metadataOrOptions: grpc.Metadata | grpc.CallOptions | null, callback: grpc.requestCallback<proto_huddly_pb.CNNStatus>): grpc.ClientUnaryCall;
  getCnnFeatureStatus(argument: proto_huddly_pb.CnnFeature, metadata: grpc.Metadata | null, options: grpc.CallOptions | null, callback: grpc.requestCallback<proto_huddly_pb.CNNStatus>): grpc.ClientUnaryCall;
  getUptime(argument: google_protobuf_empty_pb.Empty, callback: grpc.requestCallback<proto_huddly_pb.Uptime>): grpc.ClientUnaryCall;
  getUptime(argument: google_protobuf_empty_pb.Empty, metadataOrOptions: grpc.Metadata | grpc.CallOptions | null, callback: grpc.requestCallback<proto_huddly_pb.Uptime>): grpc.ClientUnaryCall;
  getUptime(argument: google_protobuf_empty_pb.Empty, metadata: grpc.Metadata | null, options: grpc.CallOptions | null, callback: grpc.requestCallback<proto_huddly_pb.Uptime>): grpc.ClientUnaryCall;
  setTimezone(argument: proto_huddly_pb.Timezone, callback: grpc.requestCallback<proto_huddly_pb.DeviceStatus>): grpc.ClientUnaryCall;
  setTimezone(argument: proto_huddly_pb.Timezone, metadataOrOptions: grpc.Metadata | grpc.CallOptions | null, callback: grpc.requestCallback<proto_huddly_pb.DeviceStatus>): grpc.ClientUnaryCall;
  setTimezone(argument: proto_huddly_pb.Timezone, metadata: grpc.Metadata | null, options: grpc.CallOptions | null, callback: grpc.requestCallback<proto_huddly_pb.DeviceStatus>): grpc.ClientUnaryCall;
  getTimezone(argument: google_protobuf_empty_pb.Empty, callback: grpc.requestCallback<proto_huddly_pb.Timezone>): grpc.ClientUnaryCall;
  getTimezone(argument: google_protobuf_empty_pb.Empty, metadataOrOptions: grpc.Metadata | grpc.CallOptions | null, callback: grpc.requestCallback<proto_huddly_pb.Timezone>): grpc.ClientUnaryCall;
  getTimezone(argument: google_protobuf_empty_pb.Empty, metadata: grpc.Metadata | null, options: grpc.CallOptions | null, callback: grpc.requestCallback<proto_huddly_pb.Timezone>): grpc.ClientUnaryCall;
  setTime(argument: google_protobuf_timestamp_pb.Timestamp, callback: grpc.requestCallback<proto_huddly_pb.DeviceStatus>): grpc.ClientUnaryCall;
  setTime(argument: google_protobuf_timestamp_pb.Timestamp, metadataOrOptions: grpc.Metadata | grpc.CallOptions | null, callback: grpc.requestCallback<proto_huddly_pb.DeviceStatus>): grpc.ClientUnaryCall;
  setTime(argument: google_protobuf_timestamp_pb.Timestamp, metadata: grpc.Metadata | null, options: grpc.CallOptions | null, callback: grpc.requestCallback<proto_huddly_pb.DeviceStatus>): grpc.ClientUnaryCall;
  getTime(argument: google_protobuf_empty_pb.Empty, callback: grpc.requestCallback<google_protobuf_timestamp_pb.Timestamp>): grpc.ClientUnaryCall;
  getTime(argument: google_protobuf_empty_pb.Empty, metadataOrOptions: grpc.Metadata | grpc.CallOptions | null, callback: grpc.requestCallback<google_protobuf_timestamp_pb.Timestamp>): grpc.ClientUnaryCall;
  getTime(argument: google_protobuf_empty_pb.Empty, metadata: grpc.Metadata | null, options: grpc.CallOptions | null, callback: grpc.requestCallback<google_protobuf_timestamp_pb.Timestamp>): grpc.ClientUnaryCall;
  setBrightness(argument: proto_huddly_pb.Brightness, callback: grpc.requestCallback<proto_huddly_pb.DeviceStatus>): grpc.ClientUnaryCall;
  setBrightness(argument: proto_huddly_pb.Brightness, metadataOrOptions: grpc.Metadata | grpc.CallOptions | null, callback: grpc.requestCallback<proto_huddly_pb.DeviceStatus>): grpc.ClientUnaryCall;
  setBrightness(argument: proto_huddly_pb.Brightness, metadata: grpc.Metadata | null, options: grpc.CallOptions | null, callback: grpc.requestCallback<proto_huddly_pb.DeviceStatus>): grpc.ClientUnaryCall;
  getBrightness(argument: google_protobuf_empty_pb.Empty, callback: grpc.requestCallback<proto_huddly_pb.Brightness>): grpc.ClientUnaryCall;
  getBrightness(argument: google_protobuf_empty_pb.Empty, metadataOrOptions: grpc.Metadata | grpc.CallOptions | null, callback: grpc.requestCallback<proto_huddly_pb.Brightness>): grpc.ClientUnaryCall;
  getBrightness(argument: google_protobuf_empty_pb.Empty, metadata: grpc.Metadata | null, options: grpc.CallOptions | null, callback: grpc.requestCallback<proto_huddly_pb.Brightness>): grpc.ClientUnaryCall;
  getRawBuffer(argument: google_protobuf_empty_pb.Empty, metadataOrOptions?: grpc.Metadata | grpc.CallOptions | null): grpc.ClientReadableStream<proto_huddly_pb.Chunk>;
  getRawBuffer(argument: google_protobuf_empty_pb.Empty, metadata?: grpc.Metadata | null, options?: grpc.CallOptions | null): grpc.ClientReadableStream<proto_huddly_pb.Chunk>;
  getVideoFormats(argument: google_protobuf_empty_pb.Empty, callback: grpc.requestCallback<proto_huddly_pb.VideoFormats>): grpc.ClientUnaryCall;
  getVideoFormats(argument: google_protobuf_empty_pb.Empty, metadataOrOptions: grpc.Metadata | grpc.CallOptions | null, callback: grpc.requestCallback<proto_huddly_pb.VideoFormats>): grpc.ClientUnaryCall;
  getVideoFormats(argument: google_protobuf_empty_pb.Empty, metadata: grpc.Metadata | null, options: grpc.CallOptions | null, callback: grpc.requestCallback<proto_huddly_pb.VideoFormats>): grpc.ClientUnaryCall;
}
