#!/bin/bash

set -eux

compodoc -w -p tsconfig.json -s -n "huddly-sdk" \
        -d "docs" \
        --minimal --customFavicon "docs_style/assets/imgs/favicon.ico" \
        --disableGraph --disableInternal --hideGenerator \
        --includesName "Additional Information" \
        --includes examples \
        -a docs_style/assets \
        -y docs_style
