const ErrorCodes = {
  UPGRADE_UPLOAD: 17,
  UPGRADE_STATUS_TIMEOUT: 12,
  UPGRADE_FAILED: 14,
  UPGRADE_RUN_FAILED: 15,
  UPGRADE_REBOOT_FAILED: 10,
  UPGRADE_INVALID_FILE: 16,
  NO_TRANSPORT: 30,
};

export default ErrorCodes;
